### ISSUE TITLE
Error rendering the pivot table tab

### ISSUE THREAD

**Issue by vanem** [y-takey/atom-pivottable#2]
There is an error when I use the command "Pivot Tableize" on an open csv file (same thing with json files). The rendering pane appear but after a while displays:
"An error occurred rendering the PivotTable UI."

I'm using the latest Atom available at the moment 1.12.7

**Comment by y-takey** [comment]
@vanem Happy new year! thanks for your report. I fixed the issue and published new version (0.0.3). could you update your atom-pivottable.

**Comment by vanem** [comment]
It works like a charm, thank you and happy new year!

If it's not too much, could you add scroll bars to the pivot table window? When the data set is too big, there seem to be no way to scroll and see the offscreen data.

(I would try to do it myself and contribute, but I'm really at js/node/atom tutorial-level)

**Comment by y-takey** [comment]
Thank you for your request! I've improved the package(to version 0.0.4), now you can scroll the pivot table window.
